name: Update Tag Index

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-tag-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Uses the GitHub provided token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install frontmatter

      - name: Run Python script
        run: |
          python getMetadata.py  # Now in the root directory

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Tag Index"
          file_pattern: metadata_output.md
          token: ${{ secrets.GITHUB_TOKEN }}  # Use token for authentication when pushing
